/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppPerfisRouteImport } from './routes/app.perfis'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppJogadoresIndexRouteImport } from './routes/app.jogadores.index'
import { Route as AppJogadoresIdRouteImport } from './routes/app.jogadores.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfisRoute = AppPerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppJogadoresIndexRoute = AppJogadoresIndexRouteImport.update({
  id: '/jogadores/',
  path: '/jogadores/',
  getParentRoute: () => AppRoute,
} as any)
const AppJogadoresIdRoute = AppJogadoresIdRouteImport.update({
  id: '/jogadores/$id',
  path: '/jogadores/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/perfis': typeof AppPerfisRoute
  '/app/': typeof AppIndexRoute
  '/app/jogadores/$id': typeof AppJogadoresIdRoute
  '/app/jogadores/': typeof AppJogadoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/perfis': typeof AppPerfisRoute
  '/app': typeof AppIndexRoute
  '/app/jogadores/$id': typeof AppJogadoresIdRoute
  '/app/jogadores': typeof AppJogadoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/perfis': typeof AppPerfisRoute
  '/app/': typeof AppIndexRoute
  '/app/jogadores/$id': typeof AppJogadoresIdRoute
  '/app/jogadores/': typeof AppJogadoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/app/dashboard'
    | '/app/perfis'
    | '/app/'
    | '/app/jogadores/$id'
    | '/app/jogadores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/app/dashboard'
    | '/app/perfis'
    | '/app'
    | '/app/jogadores/$id'
    | '/app/jogadores'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/app/dashboard'
    | '/app/perfis'
    | '/app/'
    | '/app/jogadores/$id'
    | '/app/jogadores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfis': {
      id: '/app/perfis'
      path: '/perfis'
      fullPath: '/app/perfis'
      preLoaderRoute: typeof AppPerfisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jogadores/': {
      id: '/app/jogadores/'
      path: '/jogadores'
      fullPath: '/app/jogadores/'
      preLoaderRoute: typeof AppJogadoresIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jogadores/$id': {
      id: '/app/jogadores/$id'
      path: '/jogadores/$id'
      fullPath: '/app/jogadores/$id'
      preLoaderRoute: typeof AppJogadoresIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppPerfisRoute: typeof AppPerfisRoute
  AppIndexRoute: typeof AppIndexRoute
  AppJogadoresIdRoute: typeof AppJogadoresIdRoute
  AppJogadoresIndexRoute: typeof AppJogadoresIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppPerfisRoute: AppPerfisRoute,
  AppIndexRoute: AppIndexRoute,
  AppJogadoresIdRoute: AppJogadoresIdRoute,
  AppJogadoresIndexRoute: AppJogadoresIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
